### PR TITLE
Removed nancy-ignore

### PR DESCRIPTION
**Pull request by willcAND**
### What

Deleted `.nancy-ignore` file as no longer needed.

### How to review

- Checkout branch, run `make audit` to confirm no vulnerabilities are found.

### Who can review

A member of the ONS.

### CODE REVIEW

**Review by lindenmckenzie — COMMENTED** [review]
I think we tend to leave them in but have them blank if there's nothing to ignore.

**Comment by jmgq** [comment]
> I think we tend to leave them in but have them blank if there's nothing to ignore.

@lindenmckenzie either way works for us, although we haven't come across any repo with an empty `.nancy-ignore` files yet. The majority of them don't even have this file, and the new repo generation tool does not create one. Because of these reasons, we opted to remove it, but we can bring it back and clear its contents if that's the preferred way 👍

**Comment by lindenmckenzie** [comment]
Sure - my preference would be to leave it there but empty to make it clear that's what's used to ignore vulnerabilities but it's empty right now.

**Comment by willcAND** [comment]
> Sure - my preference would be to leave it there but empty to make it clear that's what's used to ignore vulnerabilities but it's empty right now.

Re added the file and left it empty.

**Review by lindenmckenzie — APPROVED** [review]

**Pull request merged**
